### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! 

### ISSUE THREAD

**Issue by gitezri** [RajKKapadia/Transformers-Text-Classification-BERT-Blog#1]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 get_prediction('I am not happy to see you.')                                                 │
│   2                                                                                              │
│                                                                                                  │
│ in get_prediction:8                                                                              │
│                                                                                                  │
│    5 │   encoding = new_tokenizer(text, return_tensors="pt", padding="max_length", truncation    │
│    6 │   encoding = {k: v.to(trainer.model.device) for k,v in encoding.items()}                  │
│    7 │                                                                                           │
│ ❱  8 │   outputs = new_model(**encoding)                                                         │
│    9 │                                                                                           │
│   10 │   logits = outputs.logits                                                                 │
│   11                                                                                             │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl     │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py:1562 in │
│ forward                                                                                          │
│                                                                                                  │
│   1559 │   │   """                                                                               │
│   1560 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return  │
│   1561 │   │                                                                                     │
│ ❱ 1562 │   │   outputs = self.bert(                                                              │
│   1563 │   │   │   input_ids,                                                                    │
│   1564 │   │   │   attention_mask=attention_mask,                                                │
│   1565 │   │   │   token_type_ids=token_type_ids,                                                │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl     │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py:1013 in │
│ forward                                                                                          │
│                                                                                                  │
│   1010 │   │   # and head_mask is converted to shape [num_hidden_layers x batch x num_heads x s  │
│   1011 │   │   head_mask = self.get_head_mask(head_mask, self.config.num_hidden_layers)          │
│   1012 │   │                                                                                     │
│ ❱ 1013 │   │   embedding_output = self.embeddings(                                               │
│   1014 │   │   │   input_ids=input_ids,                                                          │
│   1015 │   │   │   position_ids=position_ids,                                                    │
│   1016 │   │   │   token_type_ids=token_type_ids,                                                │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl     │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py:230 in  │
│ forward                                                                                          │
│                                                                                                  │
│    227 │   │   │   │   token_type_ids = torch.zeros(input_shape, dtype=torch.long, device=self.  │
│    228 │   │                                                                                     │
│    229 │   │   if inputs_embeds is None:                                                         │
│ ❱  230 │   │   │   inputs_embeds = self.word_embeddings(input_ids)                               │
│    231 │   │   token_type_embeddings = self.token_type_embeddings(token_type_ids)                │
│    232 │   │                                                                                     │
│    233 │   │   embeddings = inputs_embeds + token_type_embeddings                                │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl     │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/modules/sparse.py:162 in forward         │
│                                                                                                  │
│   159 │   │   │   │   self.weight[self.padding_idx].fill_(0)                                     │
│   160 │                                                                                          │
│   161 │   def forward(self, input: Tensor) -> Tensor:                                            │
│ ❱ 162 │   │   return F.embedding(                                                                │
│   163 │   │   │   input, self.weight, self.padding_idx, self.max_norm,                           │
│   164 │   │   │   self.norm_type, self.scale_grad_by_freq, self.sparse)                          │
│   165                                                                                            │
│                                                                                                  │
│ /home/ezri/.local/lib/python3.10/site-packages/torch/nn/functional.py:2210 in embedding          │
│                                                                                                  │
│   2207 │   │   #   torch.embedding_renorm_                                                       │
│   2208 │   │   # remove once script supports set_grad_enabled                                    │
│   2209 │   │   _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)                    │
│ ❱ 2210 │   return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)        │
│   2211                                                                                           │
│   2212                                                                                           │
│   2213 def embedding_bag(                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when 
checking argument for argument index in method wrapper_CUDA__index_select)

**Comment by RajKKapadia** [comment]
Hi, I have updated the Jupyter Notebook and ran it one time, it works okay, I think if you pull the new updates, it will work.

**Comment by gitezri** [comment]
I sent a pull request which allows use of Intel/NVIDIA GPU.
